config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :animals do
    resources :sightings
  end
  resources :regions
  root 'animals#index'
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :sightings
  validates :name , presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :sightings
  validates :name, presence: true
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :animal
  belongs_to :region
  validates :date, presence: true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end
  def new
    @animal = Animal.new
  end
  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      flash[:notice] = "Animal successfully added!"
      redirect_to  animals_path
    else
      render :new
    end
  end
  def show
    @animal = Animal.find(params[:id])
  end
  def edit
    @animal = Animal.find(params[:id])
  end
  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      flash[:notice] = "Animal updated successfully!"
      redirect_to  animals_path
    else
      render :edit
    end
  end
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
  end


  private
  def animal_params
    params.require(:animal).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
    @regions = Region.all
  end
  def show
    @region = Region.find(params[:id])
  end
  def new
    @region = Region.new
  end
  def create
    @region = Region.new(region_params)
    if @region.save
      redirect_to regions_path
    else
      render :new
    end
  end
  def edit
    @region = Region.find(params[:id])
  end
  def destroy
    @region = Region.find(params[:id])
    @region.destroy
    redirect_to regions_path
  end
  def update
    @region = Region.find(params[:id])
    if @region.update(region_params)
      redirect_to regions_path
    else
      render :edit
    end
  end

  private
  def region_params
    params.require(:region).permit(:name)
  end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def new
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.new
  end
  def create
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new(sighting_params)
    if @sighting.save
      redirect_to animal_path(@animal)
    else
      render :new
    end
  end
  def edit
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
  end
  def update
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
    if @sighting.update(sighting_params)
      redirect_to animal_path(@animal)
    else
      render :edit
    end
  end
  def destroy
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
    @sighting.destroy
    redirect_to animal_path(@animal)
  end


  private
  def sighting_params
    params.require(:sighting).permit(:date,:longitude,:latitude,:region_id)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/_form.html.erb
<%= render "layouts/errors", :object => @animal %>


<%= form_for @animal do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/animals/edit.html.erb
<h2>Edit <%= @animal.name%></h2>

<%= render 'form'%>

app/views/animals/index.html.erb
<h1>Animals</h1>

  <ul>
    <% @animals.each do |animal| %>
    <li><%= link_to animal.name, animal_path(animal) %></li>
    <% end %>
  </ul>

  <hr>

  <%= link_to "New Animal", new_animal_path %>

app/views/animals/new.html.erb
<h2>Add a new animal</h2>
<%= render "form" %>

app/views/animals/show.html.erb
<h1><%= @animal.name%></h1>

<% if @animal.sightings.any? %>
<h4>These are sightings for <%= @animal.name%>:</h4>

<ul>
  <% @animal.sightings.each do |sighting| %>
  <li>
    <%= sighting.region.name %>
    |
    <%= sighting.date %>
    |
    <%= sighting.latitude %>
    |
    <%= sighting.longitude %>
    |
    <%= link_to "Edit", edit_animal_sighting_path(@animal, sighting) %>
    |
    <%= link_to "Delete", animal_sighting_path(@animal, sighting),
                                   :data => {:confirm => "Are you sure?",
                                                  :method => "delete"} %>
  </li>
  <% end %>
</ul>
<% else %>
<p>This animal has not been seen yet!</p>
<% end %>

<hr>
<p><%= link_to "New Sighting", new_animal_sighting_path(@animal) %></p>
<p><%= link_to "Edit Animal", edit_animal_path(@animal) %></p>
<p><%= link_to "Delete Animal", animal_path(@animal),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></p>

<p><%= link_to "Return to animals", animals_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wildlife Tracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <nav>
      <li><%= link_to "Home Page", '/' %></li>
      <li><%= link_to "Regions Page", regions_path %></li>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/regions/_form.html.erb
<%= render "layouts/errors", :object => @region %>


<%= form_for @region do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing <%= @region.name %></h1>

<%= render 'form'%>

app/views/regions/index.html.erb
<h1>Here are all regions.</h1>
<ul>
  <% @regions.each do |region| %>
  <li>
    <p><%= link_to region.name, region_path(region) %></p>
    <p><%= link_to 'Edit Region', edit_region_path(region)%>
    <%= link_to "Delete", region_path(region),
                                     :data => {:confirm => "Are you sure?",
                                                    :method => "delete"} %>
    </p>
  </li>
  <% end %>
</ul>

<hr>
<%= link_to "New Region", new_region_path %>

app/views/regions/new.html.erb
<h1>Add a new Region</h1>

<%= render "form" %>

app/views/regions/show.html.erb
<h1>The <%= @region.name%> region.</h1>
<hr>
<% if @region.sightings.any? %>
<h2>Sightings in <%=@region.name%></h2>
<ul>
  <% @region.sightings.each do |sighting| %>
  <li>
    <%= sighting.animal.name %>
    |
    <%= sighting.date %>
    |
    <%= sighting.latitude %>
    |
    <%= sighting.longitude %>
  </li>
  <% end %>
</ul>
<%else%>
<%end%>

app/views/sightings/_form.html.erb
<%= render "layouts/errors", :object => @animal %>


<%= form_for [@animal,@sighting] do |f| %>
<%= f.label :date %>
<%= f.date_field :date %>
<%= f.label :longitude %>
<%= f.text_field :longitude %>
<%= f.label :latitude %>
<%= f.text_field :latitude %>
<%= f.label :region %>

<%= f.select(:region_id) do %>
  <% Region.all.each do |r| %>
    <%= content_tag(:option, r.name, value: r.id) %>
  <% end %>
<% end %><%= f.submit %>
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing <%= @animal.name%> sighting on <%= @sighting.date%></h1>
<%= render "form"%>

app/views/sightings/new.html.erb
<h1>New <%= @animal.name %> sighting.</h1>
<%= render "form"%>